### ISSUE TITLE
Is this package listed in the APM?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/atom-language-julia#2]
sorry for posting a question here instead of an issue - but if I wanted to move to atom-language-julia from language-julia, how would I do it?

(Perhaps something in README.md?)

**Comment by spencerlyon2** [comment]
Great question.

It is not in APM yet because I am still waiting to hear from @tpoisot (author of tpoisot/language-julia) to see if he is on board supporting this package instead. Hopefully this happens soon.

If you want to use it right now, you can set it up how I did:

```shell
apm uninstall language-julia  # removing existing package
cd SOMEWHERE_TO_STORE_REPO
git clone git@github.com:JuliaLang/atom-language-julia.git
apm link atom-language-julia
```

This will create a symlink from the directory to where you cloned the repo to `~/.atom/packages`.

**Comment by sbromberger** [comment]
Perfect. Would you mind if I made a PR to README.md with that info?

**Comment by spencerlyon2** [comment]
Nope, not at all. 

Again, hopefully this is a temporary procedure that is a stop-gap for early adopters.

**Comment by sbromberger** [comment]
PR #4 submitted. Thanks.

**Comment by tpoisot** [comment]
I am.  been travelling. Will reply to email later this week end. 


Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : Spencer Lyon <notifications@github.com> 
Date : 06/13/2015  12:21 PM  (GMT-05:00) 
À : JuliaLang/atom-language-julia <atom-language-julia@noreply.github.com> 
Cc : Timothée Poisot <tim@poisotlab.io> 
Objet : Re: [atom-language-julia] Is this package listed in the APM? (#2) 

Great question.

It is not in APM yet because I am still waiting to hear from @tpoisot (author of tpoisot/language-julia) to see if he is on board supporting this package instead. Hopefully this happens soon.

If you want to use it right now, you can set it up how I did:

apm uninstall language-julia  # removing existing package
cd SOMEWHERE_TO_STORE_REPO
git clone git@github.com:JuliaLang/atom-language-julia.git
apm link atom-language-julia

This will create a symlink from the directory to where you cloned the repo to ~/.atom/packages.

**Comment by spencerlyon2** [comment]
@tpoisot that's great, thanks!

No rush. Send a message when you get back and we can collaborate - perhaps on a different platform (gitter, email, ect.)

**Comment by tpoisot** [comment]
I'll try to get this sorted out quickly. I think all is needed is to unpublish the package


Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : Spencer Lyon <notifications@github.com> 
Date : 06/13/2015  2:41 PM  (GMT-05:00) 
À : JuliaLang/atom-language-julia <atom-language-julia@noreply.github.com> 
Cc : Timothée Poisot <tim@poisotlab.io> 
Objet : Re: [atom-language-julia] Is this package listed in the APM? (#2) 

@tpoisot that's great, thanks!

No rush. Send a message when you get back and we can collaborate - perhaps on a different platform (gitter, email, ect.)

**Comment by spencerlyon2** [comment]
If you want to take a look at this and compare it to the package you have, feel free to take a bit more time. I want to make sure you are happy with any differences, seeing as you are the current maintainer of the registered language-julia package.

**Comment by spencerlyon2** [comment]
Package now registered and installable via `apm install language-julia`

**Comment by johnmyleswhite** [comment]
:cake:
