### ISSUE TITLE
Expose symbols to Atom

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/atom-language-julia#29]
So that we can use the "go to symbol" functionality.

**Comment by spencerlyon2** [comment]
Do you know the mechanism atom uses to define symbols? 

I'd like to see this too, but I don't know where to add it

**Comment by one-more-minute** [comment]
Relevant docs [here](https://github.com/atom/symbols-view)

It uses [ctags](http://ctags.sourceforge.net/), but I have no idea how to hook into that.

**Comment by spencerlyon2** [comment]
I think we can just add to their `.ctags` file something that applies on Julia scopes.

We could just start with [this](https://github.com/JuliaLang/julia/blob/master/contrib/ctags)

**Comment by one-more-minute** [comment]
I've noticed that CoffeeScript is integrated with symbols-view for individual files (though project searching doesn't work). I can't find any documentation for how that works or any mention of it in the language-coffee-script repo, though.

**Comment by spencerlyon2** [comment]
Maybe it came from [here](https://github.com/atom/symbols-view/blob/18d243be029c791696b695d6d73a0058410800f9/lib/.ctags#L1-L17)?

We could probably add the julia .ctags entry I linked to above to that same file. 

I get the symbols in atom right now, but I'm thinking that is because I added the julia .ctags entry to my local `~/.ctags`

**Comment by malmaud** [comment]
Can Atom not just get this from the Julia grammar file? Are we going to have to submit a PR to https://github.com/atom/symbols-view everytime we want to change what a Julia symbol is?

**Comment by malmaud** [comment]
Actually, its probably not a big deal  since new language features are unlikely to effect what counts as a symbol.

**Comment by spencerlyon2** [comment]
In order to use the built in symbols view package I think we would have to submit PRs there whenever the regex to define symbols needs to change. However, as you point out, I don't see that happening much.

There is an alternative package [goto](https://github.com/v3ss0n/goto) that provides the symbols view functionality based on scope names from the grammar, but it seemed a bit sluggish when I tried it out.

If you do try it out and have a better experience with it let me know.

**Comment by malmaud** [comment]
I tried ``goto`` and it doesn't seem viable - it has deprecation warnings, appears unmaintained, and crashed once. It also took a while and eventually crashed when I tried to make an index of Base (so I could could jump to any symbol in Julia).

**Comment by malmaud** [comment]
With the julia definitions in `~/.ctags`, I ran `ctags -R base` in my julia folder. Then you just bring up "Project symbols" in Atom to jump to any function defined in base - works well.

**Comment by spencerlyon2** [comment]
Closed with: https://github.com/atom/symbols-view/pull/119
