### ISSUE TITLE
Evaluating A Script Does Not Open Plot Window

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/atom-language-julia#61]
If you evaluate the whole script via Shift+Enter, the script will run but the plots won't display. Example code:

`using Gadfly`
`x = 0:.01:2`
`y = rand(length(x))`
`println(y)`
`plot(layer(x=x,y=y,Geom.line))`

If you Shift+Enter, it prints y but does not display the plot. If you then click to the line for the plot and do Ctrl+Enter it will display the plot.

**Comment by MikeInnes** [comment]
This is slightly counter-intuitive but expected – `plot` in Gadfly isn't a command to show a plot, but simply constructs a `Plot` object. Since you're not forcing that object to be displayed it doesn't show up.

You should be able to fix this easily enough by calling `display(plot(...))`.

**Comment by ChrisRackauckas** [comment]
Yup that's a quick fix. I kind of think that should be more standardized though if possible.

**Comment by MikeInnes** [comment]
In what sense – as in standardised across plotting APIs? The `display` function is completely standard as a way to display a given object.

**Comment by ChrisRackauckas** [comment]
In the sense of execution. If you execute the script different ways (the two I showed), sometimes it will display the plot and sometimes it won't. I would prefer for it to display only if called to display or always display since it took a little bit to recognize that the problem was different modes of execution. 

(Or is this just a more general thing for how Julia displays plots?)

**Comment by MikeInnes** [comment]
Yeah it's consistent with how evaluation and display works in general. If you run a Julia script (with `C-Shift-Enter` in Juno, with `julia file.jl`, or with `include("file.jl")`) then the results of the various lines are never displayed – neither the `Plot` object you created nor the vector created by `y = rand(...` and so on. On the other hand, if you specifically ask Juno or the REPL to evaluate and display the output of those lines it will happily do so. In other words: plots, vectors and other objects may be displayed very differently but they're all treated the same as far as *when* to display is concerned.

On the other hand, I can see how this is confusing coming from other environments which treat plots more as special cases, and that does bother me. The only real resolution I can see is to explicitly seperate constructors and commands within libraries, so that e.g. `Plot` creates the data and `plot(...) = display(Plot(...))`. That's what we're moving towards in Plotly – but in general, it's up to package authors to make that decision, and it's not something we can do much about within Juno itself.

Other suggestions are welcome, of course. In general it's good to be aware of and think about these issues so thanks for letting me know about it.
